apiVersion: v1
kind: Service
metadata:
  name: my-services
  labels:
    app:  myapp-service
spec:
  selector:
    app: mayank
  type: NodePort
  ports:
    - nodePort: 30005
      port: 8080
      targetPort: 8080
